### ISSUE TITLE
Set error pages and messages for different response status codes

### ISSUE THREAD

**Issue by jixuju** [flomesh-io/fgw#46]
Set error pages and messages for different response status codes, and return content based on the status codes. If it is a settings page, it will be returned through redirection; if it is a message, it will be returned directly.

1. Overall
2. Domain name level
3. Routing level

**Comment by addozhang** [comment]
@jixuju Thanks. One thing to clarify. Are you referring to this function https://nginx.org/en/docs/http/ngx_http_core_module.html#error_page?

**Comment by jixuju** [comment]
@addozhang yes
