### ISSUE TITLE
Customize the redirect response of upstream

### ISSUE THREAD

**Issue by 86542822** [flomesh-io/fgw#55]
Control the redirect response returned by the upstream:
1. remain intact
2. Modify to default value
3. Return the content of the response based on the different Locations in the response
4. Support regular expressions

Refer to nginx's http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_redirect

**Comment by wanpf** [comment]
Completed, https://github.com/flomesh-io/fgw/pull/63
